{
 "title": "K6 OTLP",
 "description": "Visualize K6 OSS results stored in Vision",
 "tags": [ "K6" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "k6ds", "label": "K6 Data Source", "query": "prometheus" },
   {
    "name": "scenario",
    "label": "Test ID",
    "query": {
     "query": "label_values(data_sent_total{provider=\"k6\"},scenario)"
    }
   },
   {
    "name": "quantile_stat",
    "label": "Trend Metrics Query",
    "query": {
     "query": "label_values(http_req_duration_milliseconds{provider=\"k6\"},stat)"
    }
   },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(vus_total{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"$quantile_stat\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "sum(irate(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(http_req_failed_total{provider=\"k6\", scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "http_req_failed"
    },
    {
     "expr": "sum(irate(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\", expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(data_sent_total{provider=\"k6\", scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(data_received_total{provider=\"k6\", scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(iteration_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"$quantile_stat\"})",
     "legendFormat": "iteration_duration_$quantile_stat"
    },
    {
     "expr": "avg(dropped_iterations_total{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "dropped_iterations"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_req_blocked_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_blocked_$quantile_stat"
    },
    {
     "expr": "avg(http_req_tls_handshaking_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat"
    },
    {
     "expr": "avg(http_req_sending_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_sending_$quantile_stat"
    },
    {
     "expr": "avg(http_req_waiting_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_waiting_$quantile_stat"
    },
    {
     "expr": "avg(http_req_receiving_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_receiving_$quantile_stat"
    },
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", expected_response=\"true\"})",
     "legendFormat": "success_http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", expected_response=\"false\"})",
     "legendFormat": "errors_http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_reqs_total{scenario=~\"$scenario\", provider=\"k6\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(http_reqs_total{scenario=~\"$scenario\", expected_response=\"false\", provider=\"k6\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    },
    {
     "expr": "sum(irate(http_reqs_total{provider=\"k6\", scenario=~\"$scenario\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p90/p95 depends on the available Quantile Stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg by(name, method, status) (http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"min\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name, method, status) (http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"max\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(name, method, status) (http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"p90\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name, method, status) (http_req_duration_milliseconds{provider=\"k6\", scenario=~\"$scenario\", stat=\"p95\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Checks Total",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(check) (checks_total{provider=\"k6\", scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Failed",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(check) (checks_total{provider=\"k6\", scenario=~\"$scenario\", value=\"0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}