name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - pkg/**
      - go.mod
      - go.sum
      - Makefile
      - register.go

permissions:
  contents: read

jobs:
  verify:
    runs-on: [ ubuntu-latest ]

    concurrency:
      # Cancel intermediate builds
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env: {}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
          args: --verbose --concurrency=2 --timeout=600s

      - name: Test with the Go CLI
        run: go test -v ./...
